spring:
  thymeleaf:
    cache: false # 이미 생성된 결과를 서버에서 계속 보관할 것인지에 대한 설정
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  #    username: sa
  #    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: src/main/resources/tempClips
      enabled: true